// Global styles here
import 'orionsoft-parts/lib/styles.css'
import 'meteor-paginated-graphql-react/lib/styles.css'
import './main.css'
import './flexbox.css'
import './helpers.css'
import './title.css'
import './content.css'
import './buttons.css'
import './animations.css'
import './label.css'
import './paginated.css'
import './texts.css'
import './tabs.css'
import './input.css'
import './colors.css'
